# Generated by Django 6.0.4 on 2026-04-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0002_incomingcorrespondence_file_letters_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('REGIONAL', 'Regional'), ('EXT_FREQUENT', 'External_Frequent'), ('EXTERNAL', 'External')], max_length=15, null=True),
        ),
    ]
